development:
  host: localhost
  username: shaji
  password: admin123
  database: clean_bee_dev_db
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432


production:
  url: <%= ENV['DATABASE_URL'] %>
