development:
  host: localhost
  username: postgres
  password: CleanBee
  database: clean_b_rider
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432


production:
  url: <%= ENV['DATABASE_URL'] %>