development:
  host: localhost
  username: postgres
  password: postgres
  database: clean_bee_dev_db
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

production:
  adapter: postgresql
  url: postgres://cblxvdpeowivwh:10b6434618df696e392b4f3b74a57c9b0de32dce6dc88ba8c24035ce3950490d@ec2-54-243-47-196.compute-1.amazonaws.com:5432/d21t7vvbga0of8
# production:
#   host: 
#   username: 
#   password: 
#   database: 
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   port: 5432
