development:
  host: localhost
  username: postgres
  password: postgres
  database: clean_bee_dev_db
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
# production:
#   host: 
#   username: 
#   password: 
#   database: 
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   port: 5432
