development:
  host: localhost
  username: postgres
  password: postgres
  database: ubwab
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

production:
  host: 
  username: 
  password: 
  database: 
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
